# Generated by Django 4.2.16 on 2026-02-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_key", models.CharField(max_length=64, unique=True)),
                ("state", models.CharField(default="WAIT_MENU", max_length=64)),
                (
                    "pending_intent",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "verify_first_name",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "verify_meter_last4",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("verified_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "in"), ("out", "out")], max_length=8
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "text"), ("voice", "voice")],
                        default="text",
                        max_length=8,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("stt_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.conversationsession",
                    ),
                ),
            ],
        ),
    ]
