# Generated by Django 4.2.16 on 2026-02-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_customer_consumptionrecord_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="pending_action_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="pending_action_params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="pending_action_preview",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="pending_action_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
